### ISSUE TITLE
Option to Specify a TestRail Run to Publish results against

### ISSUE THREAD

**Issue by xirsoi** [jenkinsci/testrail-plugin#24]

**Comment by mikec-bullhorn** [comment]
I agree that this could come in handy.

**Comment by xirsoi** [comment]
Note for implementation, this should work almost identically to how the optional Milestone works.

**Comment by xirsoi** [comment]
Try this build. My preliminary testing looks good.

https://www.dropbox.com/s/yi5o3b2bi77a7la/testrail.hpi?dl=0

**Comment by IantoMcGuckin** [comment]
Hi - for me, the drop-down box for test runs is empty.  I have created test runs, trying different options in case they needed to meet some kind of criteria to appear in the list, but it is always empty.  I've tried editing the job's config.xml and inserting a value to the `<testRun`>80`</testRun`> to see if the runtime aspect works

**Comment by IantoMcGuckin** [comment]
I can verify that the extra parameters are saving and displaying OK now (you've closed that issue)

**Comment by IantoMcGuckin** [comment]
not sure what tz you're in - any chance of looking at this asap?

**Comment by xirsoi** [comment]
Hey, the exception you're getting when you run was a simple (stupid) bug. I've fixed that, but don't know about why the runs are empty,  can you tell me if there are any errors in your browser console when you are configuring the job?

**Comment by IantoMcGuckin** [comment]
I can't see any

**Comment by IantoMcGuckin** [comment]
just looking in Firefox too (I usually use Chrome)

![image](https://user-images.githubusercontent.com/29099191/28312118-e3f349fe-6ba9-11e7-9c17-91931408a16a.png)

**Comment by IantoMcGuckin** [comment]
same - empty list

**Comment by IantoMcGuckin** [comment]
ah - hudson-behavior.js:424 Uncaught TypeError: Cannot read property 'firstChild' of undefined
    at registerValidator (hudson-behavior.js:424)
    at Array.forEach (<anonymous>)
    at behavior.js:111
    at Array.forEach (<anonymous>)
    at behavior.js:107
    at Array.forEach (<anonymous>)
    at Object.applySubtree (behavior.js:93)
    at select.js:269
hudson-behavior.js:1301 Unable to find nearby testRailProject
(anonymous) @ hudson-behavior.js:1301

is that relevant?

**Comment by IantoMcGuckin** [comment]
I see here:
![image](https://user-images.githubusercontent.com/29099191/28312822-6963e574-6bac-11e7-8295-dbe8995bfda8.png)

that 'fillTestRunItems' has 
fillDependsOn="testRailProject", whereas 'fillTestrailMilestoneItems' has
fillDependsOn="testrailProject",

so using a different case for the name

**Comment by xirsoi** [comment]
My God. This is why I miss C# and Visual Studio whenever I work on this :/

**Comment by IantoMcGuckin** [comment]
hopefully it's that simple - and I can try a new build, please?

**Comment by xirsoi** [comment]
https://www.dropbox.com/s/yi5o3b2bi77a7la/testrail.hpi?dl=0

**Comment by IantoMcGuckin** [comment]
trying it now

**Comment by IantoMcGuckin** [comment]
I still get:

**Comment by xirsoi** [comment]
You still get nothing? Damn it.

**Comment by IantoMcGuckin** [comment]
still using a different case for testRailProject

**Comment by xirsoi** [comment]
That's really weird. I've cleaned and repackaged, should be good this time: https://www.dropbox.com/s/yi5o3b2bi77a7la/testrail.hpi?dl=0

**Comment by IantoMcGuckin** [comment]
thanks - trying it now

**Comment by IantoMcGuckin** [comment]
org.json.JSONException: JSONObject["id"] not a string.
	at org.json.JSONObject.getString(JSONObject.java:658)
	at org.jenkinsci.plugins.testrail.TestRailClient.createRunFromJson(TestRailClient.java:322)
	at org.jenkinsci.plugins.testrail.TestRailClient.getRuns(TestRailClient.java:240)
	at org.jenkinsci.plugins.testrail.TestRailNotifier$DescriptorImpl.doFillTestRunItems(TestRailNotifier.java:433)
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)

**Comment by xirsoi** [comment]
Stupid library, everything is a string. That's very encouraging though, it means it pulled a test run from TestRail!

Here's the next build: https://www.dropbox.com/s/yi5o3b2bi77a7la/testrail.hpi?dl=0

**Comment by IantoMcGuckin** [comment]
trying it now

**Comment by IantoMcGuckin** [comment]
org.json.JSONException: JSONObject["milestone_id"] not a string.
	at org.json.JSONObject.getString(JSONObject.java:658)
	at org.jenkinsci.plugins.testrail.TestRailClient.createRunFromJson(TestRailClient.java:325)
	at org.jenkinsci.plugins.testrail.TestRailClient.getRuns(TestRailClient.java:240)
	at org.jenkinsci.plugins.testrail.TestRailNotifier$DescriptorImpl.doFillTestRunItems(TestRailNotifier.java:433)
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)

**Comment by xirsoi** [comment]
https://www.dropbox.com/s/yi5o3b2bi77a7la/testrail.hpi?dl=0

**Comment by IantoMcGuckin** [comment]
trying it now

**Comment by IantoMcGuckin** [comment]
org.json.JSONException: JSONObject["milestone_id"] is not an int.
	at org.json.JSONObject.getInt(JSONObject.java:540)
	at org.jenkinsci.plugins.testrail.TestRailClient.createRunFromJson(TestRailClient.java:325)
	at org.jenkinsci.plugins.testrail.TestRailClient.getRuns(TestRailClient.java:240)
	at org.jenkinsci.plugins.testrail.TestRailNotifier$DescriptorImpl.doFillTestRunItems(TestRailNotifier.java:433)
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)

**Comment by xirsoi** [comment]
Ah shit, I hadn't considered if the run didn't have a milestone.

**Comment by IantoMcGuckin** [comment]
Is that something I can work around? Or something you need to change?

**Comment by xirsoi** [comment]
Both, but I'm building an updated version of the plugin right now. Should have a link in a minute.

**Comment by xirsoi** [comment]
https://www.dropbox.com/s/yi5o3b2bi77a7la/testrail.hpi?dl=0

**Comment by IantoMcGuckin** [comment]
I've created a run with a milestone, and one without, to test both cases, trying it now

**Comment by IantoMcGuckin** [comment]
org.json.JSONException: JSONObject["description"] not a string.
	at org.json.JSONObject.getString(JSONObject.java:658)
	at org.jenkinsci.plugins.testrail.TestRailClient.createRunFromJson(TestRailClient.java:324)
	at org.jenkinsci.plugins.testrail.TestRailClient.getRuns(TestRailClient.java:240)
	at org.jenkinsci.plugins.testrail.TestRailNotifier$DescriptorImpl.doFillTestRunItems(TestRailNotifier.java:433)
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)

**Comment by IantoMcGuckin** [comment]
oh ... you're showing the test run description in the drop-down field?

**Comment by xirsoi** [comment]
That was the only useful string in the existing Run class, I just checked the API and Name is a much more useful field, I'll grab that.

**Comment by IantoMcGuckin** [comment]
Adam, let me take this opportunity to thank you for all your hard work on this.  When it is published, it will be useful to so many others, as it is now quite fully-featured for allowing the posting of test results to testrail.  As a tester, I am conscious that feedback can come across as criticism, and also that this is an open source solution that you're working on in your spare time - so many thanks for helping get this into a useful state for our company - very, very much appreciated

**Comment by xirsoi** [comment]
And I appreciate your patience with this process. I too am in QA and I know how frustrating it can be when a developer won't even do the most basic of smoke tests, like making sure a new page even loads, before handing it over to QA and wasting everyone's time.

Here's another build: https://www.dropbox.com/s/yi5o3b2bi77a7la/testrail.hpi?dl=0

**Comment by IantoMcGuckin** [comment]
just got this again:

org.json.JSONException: JSONObject["milestone_id"] not a string.
	at org.json.JSONObject.getString(JSONObject.java:658)
	at org.jenkinsci.plugins.testrail.TestRailClient.createRunFromJson(TestRailClient.java:326)
	at org.jenkinsci.plugins.testrail.TestRailClient.getRuns(TestRailClient.java:240)
	at org.jenkinsci.plugins.testrail.TestRailNotifier$DescriptorImpl.doFillTestRunItems(TestRailNotifier.java:433)
	at java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
	at org.kohsuke.stapler.Function$MethodFunction.invoke(Function.java:343)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:184)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:117)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:129)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:58)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:715)

**Comment by xirsoi** [comment]
Not sure how that crept back in, try this: https://www.dropbox.com/s/yi5o3b2bi77a7la/testrail.hpi?dl=0

**Comment by IantoMcGuckin** [comment]
that seems to have worked!  Running an actual test now to see what happens at the publish results phase (takes 10 mins, unfortunately, the only job I have configured)

**Comment by IantoMcGuckin** [comment]
will you be available for much longer today?

**Comment by xirsoi** [comment]
No, i have to leave for work. I can access github while at work, but I cannot perform any more updates.

**Comment by IantoMcGuckin** [comment]
damn - I removed the additional parameters,
<extraParameters></extraParameters>

so the runtime test revealed this at publish: 
ERROR: Build step failed with exception
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)

so I guess it's not handling that case?

trying it again with a valid json object

**Comment by xirsoi** [comment]
I thought I covered that case... I'll fix it tonight.

**Comment by xirsoi** [comment]
Did it work?

**Comment by IantoMcGuckin** [comment]
Hi - indeed it did

Here is a screenshot where I have run the test twice, reporting against the same test run:

![image](https://user-images.githubusercontent.com/29099191/28336064-7bc52966-6bf8-11e7-88c8-984dd27bc3fb.png)

**Comment by xirsoi** [comment]
Beautiful!

**Comment by IantoMcGuckin** [comment]
It only seems to list runs that are not associated with plans, however.

If I use the API call get_plan, I can see the test run I created for the plan (this is not listed in the drop down list in Jenkins).

If I use the API call get_plan, I can see the test run I created for the plan (this is not listed in the drop down list in Jenkins).

Looking at the API doc, it says (for get_runs) 
'Returns a list of test runs for a project. Only returns those test runs that are not part of a test plan (please see get_plans/get_plan for this).'

Can it be amended to also list the runs for a plan?

**Comment by IantoMcGuckin** [comment]
I also have this issue (for the extra parameters field):

![image](https://user-images.githubusercontent.com/29099191/28336923-a4a396a8-6bfb-11e7-873d-85c09035de8f.png)

In the top version field, it has not expanded the Jenkins environment variables 
In the bottom version field, I am using a static value - I can't get it to expand the env vars

**Comment by xirsoi** [comment]
I'll get the runs from test plans too, but I don't know anything about Jenkins environment variables.

**Comment by IantoMcGuckin** [comment]
Ok, any possibility of a build with the test runs from the test plans this morning so I can begin population of our love server with results?

**Comment by xirsoi** [comment]
No, I won't be able to get it done this morning, sorry ☹️

**Comment by IantoMcGuckin** [comment]
Any idea when you might be able to provide a build? Also, anyone you know who might be able to help with the Jenkins env vars in the extra parameters json object?

**Comment by IantoMcGuckin** [comment]
Can I also ask that you display the name of the testplan alongside the name of the test run if it is for a testplan?  This is because we typically have testplans e.g. 'version 7.3.0' and 'version 7.4.0' which will have all of the test suites added to them, and in the testruns drop-down, we need a way of distinguishing between the run that is for testplan 'version 7.3.0' and the run that is for 'version 7.4.0' as the run numbers will be different

**Comment by IantoMcGuckin** [comment]
I am getting this error from our live server:

![image](https://user-images.githubusercontent.com/29099191/28412834-480d48ba-6d3d-11e7-9202-d41eec1e60aa.png)

**Comment by xirsoi** [comment]
I will try to make time for this update as soon as I can. Might squeeze time in on Friday or Sunday.

Could you file a separate ticket for that error? I'm guessing that the request is simply too large.

**Comment by IantoMcGuckin** [comment]
hi, hope you enjoyed your weekend.  Any progress?  I am working around the issues, which means hand editing the jenkins config.xml files, which means that I need to make sure the edits are preserved if I open the config in Jenkins.  I am presenting what has been accomplished so far to the team on Wed (full powerpoint and show-and-tell)

**Comment by IantoMcGuckin** [comment]
also, I have one .xml file (just one, from many) which will not upload, it keeps providing the message:

Posting to index.php?/api/v2/add_results_for_cases/576 returned an error! Response from TestRail is: 
`{"error":"Field :results cannot be empty (one result is required)"`}

I cann;t see what the problem is, and have tried amending the file in many ways; by disabling tests in turn, by editing values in the file, etc., etc., but I can't deduce what the problem is.  Do you have a suitable debug environment where, if I supplied you with the file, you could tell me what is wrong with it?

**Comment by IantoMcGuckin** [comment]
Hi - any progress

**Comment by xirsoi** [comment]
Hey, not yet. I'll finally be able to make some time for this on the weekend. The TestRail API regarding test runs in test plans is stupid, but I think I can get it done on Saturday.

**Comment by IantoMcGuckin** [comment]
Any luck?

**Comment by xirsoi** [comment]
None yet

**Comment by tdurova** [comment]
I have this error too in dev branch

**Comment by michaelseno** [comment]
Hi, I know this thread is quite old but I am having the same issue as pertaining to this thread and I am not able to access the dropbox provided (beta build). here is the error I encounter. Please let me know if you need more information. Thanks

```Recording test results
Test Cases: 
  Test Cases: should return landing page 1st attempt
  Test Cases: should return landing page 2nd attempt
  Test Cases: should return landing page 3rd attempt
  Test Cases: should return landing page 4th attempt
  Test Cases: should return landing page 5th attempt
Munging test result files.
Scanning /Users/Shared/Jenkins/tmp/jenkins7488288884795341319tmp
processing jenkins7488288884795341319tmp
processing result.xml
Uploading results to TestRail.
Error pushing results to TestRail
Posting to index.php?/api/v2/add_results_for_cases/1897 returned an error! Response from TestRail is: 
{"error":"Field :results cannot be empty (one result is required)"}
Build step 'TestRail Plugin' marked build as failure
Finished: FAILURE```

**Comment by tdurova** [comment]
I would like to take part in the development of this project to fix this very critical for me bug, but is there any way to test Jenkins/Testrail/Junit integration automatically on my local environment?
