### ISSUE TITLE
some types of failures not being logged in testrail

### ISSUE THREAD

**Issue by IantoMcGuckin** [jenkinsci/testrail-plugin#29]
An example of a type of error (from the unittest .xml file) for which the results in testrail are not reported (appear as 'untested' in testrail)

`<testcase classname="webRequestFilterTest.WebRequestFilterTest" 
name="test_canFailToMatchResponseHeader" time="0.000"`>
			`<failure message="__init__() takes exactly 8 arguments (7 given)" type="TypeError"`>
`<![CDATA[Traceback (most recent call last):
  File "e:\builds\workspace\Studio_730\python\facilita\fctest\unit\webRequestFilterTest.py", line 82, in test_canFailToMatchResponseHeader
    request = self.createWebRequest()
  File "e:\builds\workspace\Studio_730\python\facilita\fctest\unit\webRequestFilterTest.py", line 32, in createWebRequest
    return HttpRequest("", "", 0, "", "", self.logWriter)
TypeError: __init__() takes exactly 8 arguments (7 given)
]]`>			`</failure`>
		`</testcase`>

**Comment by IantoMcGuckin** [comment]
opened my mistake
