### ISSUE TITLE
Duplication of tests for junit 4 reports

### ISSUE THREAD

**Issue by tdurova** [jenkinsci/testrail-plugin#32]
For example I have this xml report:
``<testsuite name="tests.country.CountryCreationPositiveSpec" time="6.1" tests="1" errors="0" skipped="0" failures="0">
<properties></properties>
<testcase name="Create new country" classname="tests.country.CountryCreationPositiveSpec" time="6.1"/></testsuite>``

There is I have only one test, "Create new country", but in TestRail, I see two tests for this Test run: 
tests.country.CountryCreationPositiveSpec and "Create new country". 

It looks like the testsuite is also was counted, but it shouldn't (from my point of view).

Is it a known issue? Is there any workaround? How can I fix it in the plugin source code?

**Comment by xirsoi** [comment]
This isn't intended behavior, nor was I aware of it. I'll take a look at this a.s.a.p.

**Comment by tdurova** [comment]
@xirsoi I used binaries from latest release https://github.com/jenkinsci/testrail-plugin/releases/tag/testrail-1.0.6

**Comment by tdurova** [comment]
@xirsoi Any update? Did you reproduce the problem?

**Comment by xirsoi** [comment]
I'm sorry, I haven't had a chance to run this through. I should be able to tomorrow. I hoped to find something obvious in the code that would indicate the problem, but had no luck.

I'll let you know what I come up with.

**Comment by xirsoi** [comment]
While I investigate this, could you give the develop branch a try?

**Comment by tdurova** [comment]
yes, will try today

**Comment by tdurova** [comment]
So develop (from 15 Feb 2018) branch doesnät work for me because of error

> processing TEST-tests.country.CountryCreationPositiveSpec.xml
Uploading results to TestRail.
ERROR: Build step failed with exception
org.json.JSONException: A JSONObject text must begin with '{' at 1 [character 2 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.json.JSONObject.<init>(JSONObject.java:194)
	at org.json.JSONObject.<init>(JSONObject.java:321)
	at org.jenkinsci.plugins.testrail.TestRailClient.addResultsForCases(TestRailClient.java:352)
	at org.jenkinsci.plugins.testrail.TestRailNotifier.perform(TestRailNotifier.java:165)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:736)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:682)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1073)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:627)
	at hudson.model.Run.execute(Run.java:1762)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:419)
Build step 'Send results to Test Rail' marked build as failure
Finished: FAILURE

**Comment by tdurova** [comment]
@xirsoi @tandibar @lucaspanjer @nakula @cris any help please?

**Comment by tdurova** [comment]
any updates on this issue?
