### ISSUE TITLE
plugin is hiding errors coming back from testrail api

### ISSUE THREAD

**Issue by dlethin** [jenkinsci/testrail-plugin#4]
We ran into an issue where the plugin was failing with the following error:

```
ERROR: Build step failed with exception
org.json.JSONException: JSONObject["title"] not found.
    at org.json.JSONObject.get(JSONObject.java:473)
    at org.json.JSONObject.getString(JSONObject.java:654)
    at org.jenkinsci.plugins.testrail.TestRailClient.createCaseFromJson(TestRailClient.java:264)
    at org.jenkinsci.plugins.testrail.TestRailClient.addCase(TestRailClient.java:278)
    at org.jenkinsci.plugins.testrail.TestRailObjects.ExistingTestCases.addCase(ExistingTestCases.java:112)
    at org.jenkinsci.plugins.testrail.TestRailNotifier.addSuite(TestRailNotifier.java:182)
    at org.jenkinsci.plugins.testrail.TestRailNotifier.perform(TestRailNotifier.java:133)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
    at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:720)
    at hudson.model.Build$BuildExecution.post2(Build.java:186)
    at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:665)
    at hudson.model.Run.execute(Run.java:1753)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:405)
Build step 'Notify TestRail' marked build as failure
Finished: FAILURE
```

The code is assuming that the request succeeds and will get the json data it needs.  However, when an error comes back in the response from the server, the plugin will get the above stack trace and the original error message will be lost.

I locally modified the source code in TestRailClient.java to look like this:

```
    private TestRailResponse httpPostInt(String path, String payload)
            throws UnsupportedEncodingException, IOException, HTTPException {
        TestRailResponse result;
        PostMethod post = new PostMethod(host + "/" + path);
        HttpClient httpclient = setUpHttpClient(post);

        try {
            StringRequestEntity requestEntity = new StringRequestEntity(
                    payload,
                    "application/json",
                    "UTF-8"
            );
            post.setRequestEntity(requestEntity);
            Integer status = httpclient.executeMethod(post);
            String body = new String(post.getResponseBody(), post.getResponseCharSet());
            System.out.println("hello START");
            System.out.println(body);
            System.out.println("hello END");
            result = new TestRailResponse(status, body);
        } finally {
            post.releaseConnection();
        }

        return result;
    }
```

Then I could see in my jenkins output the following:

```
INFO: blah #5 main build action completed: SUCCESS
hello START
{"error":"Field :custom_casestatus is a required field."}
hello END
```

Now that I know the original error, the problem was easy to resolve on my end.

Can the plugin we changed to make sure that the original error message coming back from the server is not lost and logged in the build job console log?

Thanks.

**Comment by himasimplisafe** [comment]
To resolve this issue {"error":"Field :custom_casestatus is a required field."}, we have tried to change project settings in TestRail UI by making custom field not required.

**Comment by xirsoi** [comment]
Thanks for the report, and I do accept pull requests.

I'll take a look at this this weekend and see how I can improve the logging and error handling.
