### ISSUE TITLE
Error xml parsing with long timeout value

### ISSUE THREAD

**Issue by Vadim2305** [jenkinsci/testrail-plugin#44]
Hello, I get error: java.lang.NumberFormatException : For input string: "3,683.445" 
when my xml report is parsing. It looks like java can't convert value 3,683.445 to the numeric format because symbol comma "," present in the string. Could you fix this issue, please?

`ERROR: Build step failed with exception
java.lang.NumberFormatException: For input string: "3,683.445"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:451)
	at com.sun.xml.internal.bind.DatatypeConverterImpl._parseFloat(DatatypeConverterImpl.java:185)
	at com.sun.xml.internal.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$20.parse(RuntimeBuiltinLeafInfoImpl.java:750)
	at com.sun.xml.internal.bind.v2.model.impl.RuntimeBuiltinLeafInfoImpl$20.parse(RuntimeBuiltinLeafInfoImpl.java:748)
	at com.sun.xml.internal.bind.v2.runtime.reflect.TransducedAccessor$CompositeTransducedAccessorImpl.parse(TransducedAccessor.java:230)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.StructureLoader.startElement(StructureLoader.java:195)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:559)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:538)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:153)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:380)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2787)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:118)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:510)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:243)
	at com.sun.xml.internal.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:214)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:157)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:162)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:171)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:189)
	at org.jenkinsci.plugins.testrail.JunitResults.JUnitResults$1$1.visit(JUnitResults.java:70)
	at hudson.util.DirScanner.scanSingle(DirScanner.java:44)
	at hudson.util.DirScanner$Glob.scan(DirScanner.java:126)
	at org.jenkinsci.plugins.testrail.JunitResults.JUnitResults$1.invoke(JUnitResults.java:65)
	at org.jenkinsci.plugins.testrail.JunitResults.JUnitResults$1.invoke(JUnitResults.java:62)
	at hudson.FilePath.act(FilePath.java:1078)
	at hudson.FilePath.act(FilePath.java:1061)
	at org.jenkinsci.plugins.testrail.JunitResults.JUnitResults.slurpTestResults(JUnitResults.java:62)
	at org.jenkinsci.plugins.testrail.JunitResults.JUnitResults.<init>(JUnitResults.java:49)
	at org.jenkinsci.plugins.testrail.TestRailNotifier.perform(TestRailNotifier.java:142)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:744)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.post2(MavenModuleSetBuild.java:1073)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1835)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:543)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'Send results to Test Rail' marked build as failure
Finished: FAILURE`

Link to the xml file https://monosnap.com/file/QtCrxnL8lvrB6julUtJCNCjODPqL8H

**Comment by xirsoi** [comment]
I'll look into it, but I suspect there's not a lot I can do because of the way marshaling and unmarshaling work in Java.

**Comment by xirsoi** [comment]
Sorry, but you're going to have to find a way to alter the format your results are output, there's nothing I can do here.
