### ISSUE TITLE
Implementation of JAXB-API has not been found on module path or classpath while munging test result files

### ISSUE THREAD

**Issue by Dereliass** [jenkinsci/testrail-plugin#52]
Hello! I am trying to use Testrail plugin for setting statuses (failed/passed) for test cases in the Testrail. Tests during the execution of the Jenkins job are run correctly, the maven surefire xml reports are generated correctly, then the Testrail plugin starts working. He correctly accesses the Testrail via api, pulls up the names of test cases from the test suite. But further, at the stage "Munging test result files." job failes with the next error message:
```
Test Cases: 
  Unit tests: High level Assembler program Unit-Test
  Unit tests: Cobol program Unit-Test
  Unit tests: PL/I program Unit-Test
Munging test result files.
Implementation of JAXB-API has not been found on module path or classpath.
ERROR: Build step failed with exception
java.lang.NullPointerException
	at org.jenkinsci.plugins.testrail.TestRailNotifier.perform(TestRailNotifier.java:141)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:112)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1919)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Build step 'TestRail Plugin' changed build result to FAILURE
Build step 'TestRail Plugin' marked build as failure
Finished: FAILURE
```

I've tried to fix this issue by adding missing dependencies in pom.xml, [by using this topic](https://stackoverflow.com/questions/51916221/javax-xml-bind-jaxbexception-implementation-of-jaxb-api-has-not-been-found-on-mo), but it didn't help. 
At the same time, the `mvn clean package` runs successfully, no errors occurred. 
I attach my modified pom.xml here: [pom.txt](https://github.com/jenkinsci/testrail-plugin/files/5471034/pom.txt)

Could you help with solving this problem? This is the first time I meet such a problem, I will be very grateful for any help!

**Comment by xirsoi** [comment]
Which version of Java and Jenkins are you using for your environment?
This seems like maybe some kind of version mismatch between Java, Jenkins, JAXB, and the Testrail plugin.

**Comment by Dereliass** [comment]
Thanks for the answer! This was indeed an environment error that I missed... Now it has been solved.

But now I ran into a new problem:
```
Test Cases: 
  unittest.Unit_Test: High_level_Assembler_Unit_Test
  unittest.Unit_Test: Cobol_Unit_Test
  unittest.Unit_Test: PL_I_Unit_Test
Munging test result files.
Scanning /tmp/jenkins5104778875532388697
processing jenkins5104778875532388697
processing TEST-unittest.Unit_Test.xml
Uploading results to TestRail.
Error pushing results to TestRail
Posting to index.php?/api/v2/add_results_for_cases/18 returned an error! Response from TestRail is: 
{"error":"Field :results cannot be empty (one result is required)"}
ERROR: Build step failed with exception
java.lang.NullPointerException
	at org.jenkinsci.plugins.testrail.TestRailNotifier.perform(TestRailNotifier.java:166)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:112)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1919)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Build step 'TestRail Plugin' changed build result to FAILURE
```

I have already looked at other same issues. However, option ["section names in Testrail didn't match the test suite in the xml"](https://github.com/jenkinsci/testrail-plugin/issues/38) didn't help to resolve this problem.

Here is my TEST-unittest.Unit_Test.xml result report: 
[TEST-unittest.Unit_Test.txt](https://github.com/jenkinsci/testrail-plugin/files/5471536/TEST-unittest.Unit_Test.txt)

The report contains the name of the test suite (<testsuite name="unittest.Unit_Test">) and three test cases.
The corresponding test suite (Test Unit Test) in the Testrail has a section - "unittest.Unit_Test", which corresponds to the name of the test suite from the JUnit report.
![Screenshoot](https://user-images.githubusercontent.com/49617806/97811501-0e8c3180-1c8c-11eb-8dca-71d9fabb764b.png)

But the error still occurs. Perhaps, maybe I need to specify some additional parameters for the test cases in the Testrail, or am I doing something wrong?
Could you please help with this problem? Thanks in advance!

**Comment by voloxastik** [comment]
Hi @Dereliass!
Can you provide working versions of the dependencies?
