### ISSUE TITLE
Error pushing results to TestRail "error":"Field :results cannot be empty (one result is required)"

### ISSUE THREAD

**Issue by Dereliass** [jenkinsci/testrail-plugin#53]
Hello! I'm facing problem - when starting Jenkins job, the plugin cannot process the JUnit .xml surefire report correctly.
I have already looked at other same issues. However, option ["section names in Testrail didn't match the test suite in the xml"](https://github.com/jenkinsci/testrail-plugin/issues/38) didn't help to resolve this problem.
```
Test Cases: 
  unittest.Unit_Test: High_level_Assembler_Unit_Test
  unittest.Unit_Test: Cobol_Unit_Test
  unittest.Unit_Test: PL_I_Unit_Test
Munging test result files.
Scanning /tmp/jenkins5104778875532388697
processing jenkins5104778875532388697
processing TEST-unittest.Unit_Test.xml
Uploading results to TestRail.
Error pushing results to TestRail
Posting to index.php?/api/v2/add_results_for_cases/18 returned an error! Response from TestRail is: 
{"error":"Field :results cannot be empty (one result is required)"}
ERROR: Build step failed with exception
java.lang.NullPointerException
	at org.jenkinsci.plugins.testrail.TestRailNotifier.perform(TestRailNotifier.java:166)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:112)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:78)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:741)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:690)
	at hudson.model.Build$BuildExecution.post2(Build.java:186)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:635)
	at hudson.model.Run.execute(Run.java:1919)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:428)
Build step 'TestRail Plugin' changed build result to FAILURE
```

Here is my TEST-unittest.Unit_Test.xml result report: 
[TEST-unittest.Unit_Test.txt](https://github.com/jenkinsci/testrail-plugin/files/5471536/TEST-unittest.Unit_Test.txt)

The report contains the name of the test suite (<testsuite name="unittest.Unit_Test">) and three test cases.
The corresponding test suite (Test Unit Test) in the Testrail has a section - "unittest.Unit_Test", which corresponds to the name of the test suite from the JUnit report.
![Screenshoot](https://user-images.githubusercontent.com/49617806/97811606-c7527080-1c8c-11eb-9121-81a78b310a1c.png)

But the error still occurs. Perhaps, maybe I need to specify some additional parameters for the test cases in the Testrail, or am I doing something wrong?
Could you please help with this problem? Thanks in advance!

**Comment by xirsoi** [comment]
Unfortunately the plugin does not currently support the Surefire schema, only the xUnit schema, as described here: https://gist.github.com/jclosure/45d7005d120d90ba6430130356e4cd61
