### ISSUE TITLE
Case sensitive problem in JAXB

### ISSUE THREAD

**Issue by zerojk** [jenkinsci/testrail-plugin#57]
Hi Adam,

First of all, thank your for your project :)

I've been working trying to link an instance of jenkins with other of testrail.
I was trying to upload different files of JUnit results. In fact, I was reading a previous problem related with the error:

```
`Building in workspace /var/jenkins_home/workspace/test
[test] $ /bin/sh -xe /tmp/jenkins8632613915616738744.sh
+ cp /var/tmp/loguito.xml ./
+ cp /var/tmp/log.xml ./
+ cp /var/tmp/sample-junit.xml ./
+ cp /var/tmp/lg2.xml ./
+ cat lg2.xml
<?xml version="1.0" encoding="UTF-8" ?>
<testsuite tests="1" failures="0" name="com.javacodegeeks.examples.junitmavenexample.CalculatorTest" id="2" time="0.007" errors="0" skipped="0">
  <properties>
    <property name="java.runtime.name" value="Java(TM) SE Runtime Environment"/>
    <property name=```
"java.vm.version" value="11.0.10+8-LTS-162"/>
    <property name="sun.boot.library.path" value="/usr/lib/jvm/jdk-11.0.10/lib"/>    
    <property name="sun.cpu.endian" value="little"/>
    <property name="java.vendor.version" value="18.9"/>
    <property name="sun.desktop" value="gnome"/>
    <property name="sun.cpu.isalist" value=""/>
  </properties>
  <testcase classname="com.javacodegeeks.examples.junitmavenexample.CalculatorTest" name="casito" time="0.002" id="12"/>
</testsuite>
Test Cases: 
  nombreseccion: caso1
Munging test result files.
Scanning /tmp/jenkins2664546775412482457
processing jenkins2664546775412482457
processing lg2.xml
Uploading results to TestRail.
Error pushing results to TestRail
Posting to index.php?/api/v2/add_results_for_cases/40 returned an error! Response from TestRail is: 
{"error":"Field :results cannot be empty (one result is required)"}      <-------------------------------
ERROR: Build step failed with exception
java.lang.NullPointerException
	at org.jenkinsci.plugins.testrail.TestRailNotifier.perform(TestRailNotifier.java:166)
	at jenkins.tasks.SimpleBuildStep.perform(SimpleBuildStep.java:123)
	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:80)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:804)
	at hudson.model.AbstractBuild$AbstractBuildExecution.performAllBuildSteps(AbstractBuild.java:753)
	at hudson.model.Build$BuildExecution.post2(Build.java:177)
	at hudson.model.AbstractBuild$AbstractBuildExecution.post(AbstractBuild.java:698)
	at hudson.model.Run.execute(Run.java:1932)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:97)
	at hudson.model.Executor.run(Executor.java:429)
Build step 'TestRail Plugin' changed build result to FAILURE
Build step 'TestRail Plugin' marked build as failure
Finished: FAILURE`
```

I was trying changing...EVERYTHING in the result file...without succcess.

But, well, my last attempt was download the project and try to see what was parsing from the result XML.
Currently I'm working on Ubuntu 20.04 (I don't know if matters)
Trying to parse the results file that you can see at the beginning of the code, the output on console was:

```
javax.xml.bind.UnmarshalException: elemento inesperado (URI:"", local:"testsuite"). Los elementos esperados son <{}testSuite>,<{}testSuites>     <-------------------------
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.handleEvent(UnmarshallingContext.java:744)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:262)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportError(Loader.java:257)
	at com.sun.xml.bind.v2.runtime.unmarshaller.Loader.reportUnexpectedChildElement(Loader.java:124)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext$DefaultRootLoader.childElement(UnmarshallingContext.java:1149)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext._startElement(UnmarshallingContext.java:574)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallingContext.startElement(UnmarshallingContext.java:556)
	at com.sun.xml.bind.v2.runtime.unmarshaller.SAXConnector.startElement(SAXConnector.java:168)
	at org.apache.xerces.parsers.AbstractSAXParser.startElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl.scanStartElement(Unknown Source)
	at org.apache.xerces.impl.XMLNSDocumentScannerImpl$NSContentDispatcher.scanRootElementHook(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl$FragmentContentDispatcher.dispatch(Unknown Source)
	at org.apache.xerces.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XML11Configuration.parse(Unknown Source)
	at org.apache.xerces.parsers.XMLParser.parse(Unknown Source)
	at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal0(UnmarshallerImpl.java:258)
	at com.sun.xml.bind.v2.runtime.unmarshaller.UnmarshallerImpl.unmarshal(UnmarshallerImpl.java:229)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:170)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:209)
	at javax.xml.bind.helpers.AbstractUnmarshallerImpl.unmarshal(AbstractUnmarshallerImpl.java:194)
	at org.jenkinsci.plugins.testrail.JUnit.JUnitResults$1$1.visit(JUnitResults.java:77)
	at hudson.util.DirScanner.scanSingle(DirScanner.java:49)
	at hudson.util.DirScanner$Glob.scan(DirScanner.java:131)
	at org.jenkinsci.plugins.testrail.JUnit.JUnitResults$1.invoke(JUnitResults.java:72)
	at org.jenkinsci.plugins.testrail.JUnit.JUnitResults$1.invoke(JUnitResults.java:1)
	at hudson.FilePath.act(FilePath.java:990)
	at hudson.FilePath.act(FilePath.java:968)
	at org.jenkinsci.plugins.testrail.JUnit.JUnitResults.slurpTestResults(JUnitResults.java:67)
	at org.jenkinsci.plugins.testrail.JUnit.JUnitResults.<init>(JUnitResults.java:54)
	at org.jenkinsci.plugins.testrail.JUnit.MiPrueba.main(MiPrueba.java:18)
```
OK...cause of all this mess has been a camelcase applied by the JAXB class when is parsing the tags "testsuite" and "testsuites".

When I changed them to "testSuite" and "testSuites"...solved.

This ticket is only to advise you that could be a problem with some versions of JAXB dependencies.

If I can help you with something, please, don't hesitate contact me,

regards, and thank you for your attention!

**Comment by xirsoi** [comment]
Interesting, thanks for the report and the investigation!
I'm too tired to look at this right this moment, so as a note for my future self, this SO might prove helpful: https://stackoverflow.com/questions/4375176/how-to-ignore-casing-of-element-names-in-jaxb

**Comment by zerojk** [comment]
Thank you for your response, Adam :)

Don't worry, I only checked this issue and thought to tell you.

Thank you for the link too, I was checking it and I understand what could be happening. Anyway, I'll try to check it on the source code.

Have a good day!

**Comment by zerojk** [comment]
Pull request

#58
